const bcrypt = require('bcrypt');
const DataService = require('../services/dataService');
const DbService = require('../services/dbService');
const config = require('../config');
const webauthnService = require('../services/webauthnService');
const { getRpIDFromOrigin } = require('../services/webauthnService');

// Use database if available, otherwise fall back to JSON files
const usersService = config.database.useDatabase
  ? new DbService('users')
  : new DataService(config.paths.usersFile);

async function login(req, res, next) {
  try {
    const { username, password } = req.body;

    if (!username || !password) {
      return res.status(400).json({ error: 'Username and password are required' });
    }

    const users = await usersService.findAll();
    const user = users.find(u => u.username === username);

    if (!user) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    const valid = await bcrypt.compare(password, user.password);
    if (!valid) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    req.session.userId = user.id;
    req.session.username = user.username;
    res.json({ success: true, username: user.username });
  } catch (error) {
    next(error);
  }
}

function logout(req, res) {
  req.session.destroy();
  res.json({ success: true });
}

async function getStatus(req, res) {
  if (req.session && req.session.userId) {
    const user = await usersService.findById(req.session.userId);
    res.json({
      authenticated: true,
      username: req.session.username,
      hasPasskey: user && user.webauthnCredentials && user.webauthnCredentials.length > 0
    });
  } else {
    res.json({ authenticated: false });
  }
}

function getCsrfToken(req, res) {
  // Token is already generated by generateCsrfToken middleware
  res.json({ csrfToken: req.session.csrfToken || null });
}

// WebAuthn Registration - Start
async function startWebAuthnRegistration(req, res, next) {
  try {
    const { username } = req.body;

    if (!username) {
      return res.status(400).json({ error: 'Username is required' });
    }

    const users = await usersService.findAll();
    const user = users.find(u => u.username === username);

    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Ensure webauthnCredentials array exists
    if (!user.webauthnCredentials) {
      user.webauthnCredentials = [];
      // Update user to persist the empty array
      await usersService.updateById(user.id, { webauthnCredentials: [] });
    }

    // Check if user already has a passkey (we only allow one per user)
    if (user.webauthnCredentials.length > 0) {
      return res.status(400).json({ error: 'User already has a passkey registered' });
    }

    const existingCredentials = user.webauthnCredentials;
    
    try {
      // Get origin from request (handle Railway proxy)
      const protocol = req.headers['x-forwarded-proto'] || (req.secure ? 'https' : 'http');
      const host = req.headers.host || req.get('host');
      const origin = `${protocol}://${host}`;
      const options = await webauthnService.generateRegistrationOptionsForUser(
        user.id,
        user.username,
        existingCredentials,
        origin
      );

      // Store challenge in session
      req.session.webauthnChallenge = options.challenge;
      req.session.webauthnUserId = user.id;
      req.session.webauthnType = 'registration';

      res.json(options);
    } catch (error) {
      console.error('Error in startWebAuthnRegistration:', error);
      console.error('Error stack:', error.stack);
      return res.status(500).json({ 
        error: 'Failed to generate registration options',
        details: error.message,
        stack: process.env.NODE_ENV !== 'production' ? error.stack : undefined
      });
    }
  } catch (error) {
    console.error('Error in startWebAuthnRegistration:', error);
    next(error);
  }
}

// WebAuthn Registration - Finish
async function finishWebAuthnRegistration(req, res, next) {
  try {
    const { response } = req.body;

    if (!response) {
      return res.status(400).json({ error: 'Registration response is required' });
    }
    
    // Validate response structure before proceeding
    if (!response.id) {
      return res.status(400).json({ error: 'Registration response missing id field' });
    }
    
    if (!response.type || response.type !== 'public-key') {
      return res.status(400).json({ 
        error: `Invalid response type: ${response.type || 'missing'}. Expected 'public-key'` 
      });
    }
    
    if (!response.response) {
      return res.status(400).json({ error: 'Registration response missing response object' });
    }
    
    if (!response.response.clientDataJSON) {
      return res.status(400).json({ error: 'Registration response missing clientDataJSON' });
    }
    
    if (!response.response.attestationObject) {
      return res.status(400).json({ error: 'Registration response missing attestationObject' });
    }

    // Verify session state
    if (!req.session.webauthnChallenge || 
        !req.session.webauthnUserId || 
        req.session.webauthnType !== 'registration') {
      return res.status(400).json({ error: 'Invalid registration session' });
    }

    const userId = req.session.webauthnUserId;
    const user = await usersService.findById(userId);

    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Get origin from request (handle Railway proxy)
    const protocol = req.headers['x-forwarded-proto'] || (req.secure ? 'https' : 'http');
    const host = req.headers.host || req.get('host');
    const origin = `${protocol}://${host}`;

    // Get rpID from origin
    const rpID = getRpIDFromOrigin(origin);

    // Create options object with stored challenge
    const storedChallenge = req.session.webauthnChallenge;
    const options = {
      challenge: storedChallenge,
      rpID: rpID,
      origin: origin
    };

    try {
      console.log('Starting registration verification:', {
        userId,
        username: user.username,
        origin,
        rpID: options.rpID,
        hasResponse: !!response,
        responseId: response?.id,
        responseType: response?.type,
        storedChallenge: storedChallenge ? storedChallenge.substring(0, 20) + '...' : 'MISSING',
        storedChallengeLength: storedChallenge?.length,
        responseChallenge: response?.response?.clientDataJSON ? 'present' : 'missing'
      });

      const verification = await webauthnService.verifyRegistration(options, response, origin);

      if (!verification.verified) {
        console.error('Registration verification failed - not verified');
        return res.status(400).json({ error: 'Registration verification failed' });
      }

      console.log('Registration verified successfully');

      // Validate the credential before saving
      const newCredential = verification.credential;
      if (!newCredential || typeof newCredential !== 'object') {
        console.error('Invalid credential from verification:', newCredential);
        return res.status(500).json({ error: 'Invalid credential data received' });
      }
      if (!newCredential.id || typeof newCredential.id !== 'string') {
        console.error('Credential missing valid id:', newCredential);
        return res.status(500).json({ error: 'Credential missing valid id' });
      }
      if (!newCredential.publicKey || typeof newCredential.publicKey !== 'string') {
        console.error('Credential missing valid publicKey:', newCredential);
        return res.status(500).json({ error: 'Credential missing valid publicKey' });
      }

      console.log('Saving credential:', {
        id: newCredential.id.substring(0, 20) + '...',
        idType: typeof newCredential.id,
        publicKeyType: typeof newCredential.publicKey,
        counter: newCredential.counter
      });

      // Add credential to user
      const updatedCredentials = Array.isArray(user.webauthnCredentials) ? [...user.webauthnCredentials] : [];
      updatedCredentials.push(newCredential);

      console.log('Updating user with credentials:', {
        count: updatedCredentials.length,
        credentialTypes: updatedCredentials.map(c => ({ idType: typeof c.id, pkType: typeof c.publicKey }))
      });

      await usersService.updateById(userId, {
        webauthnCredentials: updatedCredentials
      });

      // Clear session
      delete req.session.webauthnChallenge;
      delete req.session.webauthnUserId;
      delete req.session.webauthnType;

      res.json({ success: true, message: 'Passkey registered successfully' });
    } catch (error) {
      console.error('Error in finishWebAuthnRegistration verification:', error);
      console.error('Error stack:', error.stack);
      console.error('Error name:', error.name);
      console.error('Error message:', error.message);
      
      // Return more detailed error information
      const errorResponse = {
        error: 'Registration verification failed',
        details: error.message || 'Unknown error',
        errorName: error.name
      };
      
      // Provide user-friendly message for user verification errors
      if (error.message && error.message.includes('user could not be verified')) {
        errorResponse.userMessage = 'Dashlane requires verification. Please unlock Dashlane or complete any verification prompts (PIN, fingerprint, face ID) when Dashlane asks, then try registering again.';
      } else if (error.message && error.message.includes('User verification was required')) {
        errorResponse.userMessage = 'Dashlane requires verification. Please unlock Dashlane or complete any verification prompts when asked, then try registering again.';
      }
      
      // Include stack trace in development
      if (process.env.NODE_ENV !== 'production') {
        errorResponse.stack = error.stack;
      }
      
      // Include additional context if available
      if (error.cause) {
        errorResponse.cause = error.cause;
      }
      
      return res.status(500).json(errorResponse);
    }
  } catch (error) {
    console.error('Error in finishWebAuthnRegistration:', error);
    next(error);
  }
}

// WebAuthn Authentication - Start
async function startWebAuthnLogin(req, res, next) {
  try {
    const { username } = req.body;

    if (!username) {
      return res.status(400).json({ error: 'Username is required' });
    }

    const users = await usersService.findAll();
    const user = users.find(u => u.username === username);

    if (!user) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    // Check if user has passkey
    if (!user.webauthnCredentials || user.webauthnCredentials.length === 0) {
      return res.status(400).json({ error: 'No passkey registered for this user' });
    }

    // Log credential format for debugging
    console.log('WebAuthn login - credentials from DB:', {
      type: typeof user.webauthnCredentials,
      isArray: Array.isArray(user.webauthnCredentials),
      length: user.webauthnCredentials?.length,
      raw: JSON.stringify(user.webauthnCredentials).substring(0, 500)
    });

    // Validate and normalize credentials
    let credentials = user.webauthnCredentials;

    // Handle case where credentials might still be a string (double-encoded)
    if (typeof credentials === 'string') {
      try {
        credentials = JSON.parse(credentials);
        console.log('Parsed credentials from string');
      } catch (e) {
        console.error('Failed to parse credentials string:', e);
        return res.status(500).json({ error: 'Corrupted credential data. Please re-register your passkey.' });
      }
    }

    // Validate each credential has required fields
    if (!Array.isArray(credentials)) {
      console.error('Credentials is not an array:', typeof credentials);
      return res.status(500).json({ error: 'Invalid credential format. Please re-register your passkey.' });
    }

    const validCredentials = credentials.filter(cred => {
      if (!cred || typeof cred !== 'object') {
        console.error('Invalid credential object:', cred);
        return false;
      }
      if (!cred.id || typeof cred.id !== 'string') {
        console.error('Credential missing valid id:', { id: cred.id, type: typeof cred.id });
        return false;
      }
      if (!cred.publicKey || typeof cred.publicKey !== 'string') {
        console.error('Credential missing valid publicKey:', { publicKey: cred.publicKey, type: typeof cred.publicKey });
        return false;
      }
      return true;
    });

    if (validCredentials.length === 0) {
      console.error('No valid credentials found after filtering');
      return res.status(400).json({
        error: 'No valid passkeys found. Your passkey data may be corrupted. Please re-register.'
      });
    }

    console.log(`Found ${validCredentials.length} valid credentials out of ${credentials.length}`);

    // Get origin from request (handle Railway proxy)
    const protocol = req.headers['x-forwarded-proto'] || (req.secure ? 'https' : 'http');
    const host = req.headers.host || req.get('host');
    const origin = `${protocol}://${host}`;
    try {
      const options = await webauthnService.generateAuthenticationOptionsForUser(
        user.id,
        validCredentials,
        origin
      );

      // Store challenge and user info in session
      req.session.webauthnChallenge = options.challenge;
      req.session.webauthnUserId = user.id;
      req.session.webauthnType = 'authentication';

      res.json(options);
    } catch (error) {
      console.error('Error in startWebAuthnLogin:', error);
      console.error('Error stack:', error.stack);
      console.error('User credentials:', user.webauthnCredentials?.map(c => ({
        id: c.id,
        idType: typeof c.id,
        idLength: c.id?.length
      })));
      return res.status(500).json({
        error: 'Failed to generate authentication options',
        details: error.message,
        stack: process.env.NODE_ENV !== 'production' ? error.stack : undefined
      });
    }
  } catch (error) {
    console.error('Error in startWebAuthnLogin (outer):', error);
    next(error);
  }
}

// WebAuthn Authentication - Finish
async function finishWebAuthnLogin(req, res, next) {
  try {
    const { response } = req.body;

    if (!response) {
      return res.status(400).json({ error: 'Authentication response is required' });
    }

    // Verify session state
    if (!req.session.webauthnChallenge ||
        !req.session.webauthnUserId ||
        req.session.webauthnType !== 'authentication') {
      return res.status(400).json({ error: 'Invalid authentication session' });
    }

    const userId = req.session.webauthnUserId;
    const user = await usersService.findById(userId);

    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Find the credential that matches the response
    // SimpleWebAuthn returns id as base64url string
    const credentialId = response.id;
    
    // Try to find credential by matching the base64url ID
    const credential = user.webauthnCredentials.find(
      cred => cred.id === credentialId
    );

    if (!credential) {
      console.error('Credential not found. Response ID:', credentialId);
      console.error('Available credentials:', user.webauthnCredentials.map(c => c.id));
      return res.status(400).json({ error: 'Credential not found. Please register a new passkey.' });
    }

    // Get origin from request (handle Railway proxy)
    const protocol = req.headers['x-forwarded-proto'] || (req.secure ? 'https' : 'http');
    const host = req.headers.host || req.get('host');
    const origin = `${protocol}://${host}`;
    
    // Create options object with stored challenge
    const options = {
      challenge: req.session.webauthnChallenge,
      rpID: config.webauthn.rpID,
      origin: origin
    };

    const verification = await webauthnService.verifyAuthentication(
      options,
      response,
      credential,
      origin
    );

    if (!verification.verified) {
      return res.status(401).json({ error: 'Authentication verification failed' });
    }

    // Update credential counter (replay attack prevention)
    const credentialIndex = user.webauthnCredentials.findIndex(
      cred => cred.id === credentialId
    );
    if (credentialIndex !== -1) {
      user.webauthnCredentials[credentialIndex].counter = verification.newCounter;
      await usersService.updateById(userId, {
        webauthnCredentials: user.webauthnCredentials
      });
    }

    // Create session
    req.session.userId = user.id;
    req.session.username = user.username;

    // Clear WebAuthn session
    delete req.session.webauthnChallenge;
    delete req.session.webauthnUserId;
    delete req.session.webauthnType;

    res.json({ success: true, username: user.username });
  } catch (error) {
    next(error);
  }
}

module.exports = {
  login,
  logout,
  getStatus,
  getCsrfToken,
  startWebAuthnRegistration,
  finishWebAuthnRegistration,
  startWebAuthnLogin,
  finishWebAuthnLogin
};




